default: &default
  host: <%= ENV["HOST"] %>
  redis_url:
    <%= ENV['REDISTOGO_URL'] || ENV['REDIS_URL'] || 'redis://localhost:6379/1'%>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
